bind 0.0.0.0
port 6379
timeout 300
tcp-keepalive 60
tcp-backlog 511

maxmemory 400mb
maxmemory-policy volatile-lru

save ""
appendonly no

databases 2
loglevel warning
logfile ""

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes